name: Deploy on Github Pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DEPLOY_BRANCH: gh-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

      # - name: Unit test
      #   run: npm run test:unit

      # - name: Integration test
      #   run: npm run test:e2e:headless
      #   env:
      #     # See https://docs.cypress.io/guides/guides/environment-variables.html
      #     CYPRESS_TIMESIDE_BASE_URL: ${{ secrets.TIMESIDE_BASE_URL_E2E_TEST }}
      #     CYPRESS_TIMESIDE_USER: ${{ secrets.TIMESIDE_USER_E2E_TEST }}
      #     CYPRESS_TIMESIDE_PASS: ${{ secrets.TIMESIDE_PASS_E2E_TEST }}

      # Generates `dist/` directory
      - name: Build
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: "$DEPLOY_BRANCH" # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
